include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_super_parameters: true
    avoid_dynamic_calls: true
    unnecessary_lambdas: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    always_put_required_named_parameters_first: true
    use_string_buffers: true
